filebeat.inputs:
- type: log
  paths:
    - /var/log/nginx/*.log
  fields:
    nginx_service: nginx   # <-- renamed to avoid conflict
  fields_under_root: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
